MIT License

Copyright (c) 2026 Pankaj Garg

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

### Research & Scientific Disclaimer

The bioactivity, toxicity, and pharmacokinetic predictions generated by Rogveda are computed using *in-silico* machine learning models and cheminformatics heuristics. 

- **Research Purposes Only**: This software is intended strictly for academic, research, and educational exploration in computational chemistry and drug discovery.
- **No Clinical or Medical Advice**: Output from this platform must **not** be construed as medical diagnosis, clinical advice, or a guarantee of biological safety or therapeutic efficacy.
- **Experimental Verification**: Any candidate molecules identified or evaluated by Rogveda must undergo rigorous *in-vitro*, *in-vivo*, and regulatory validation before any biological or medical application.
